config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Push subscriptions and notifications
  resource :push_subscriptions, only: [:create, :destroy]

  get "feed", to: "rss#index", format: "rss"
  get "sitemap", to: "sitemap#index", defaults: {format: "xml"}

  resource :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :photos, except: [:show, :destroy]
  end

  scope "/admin" do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
  get "/admin" => "admin/photos#index"

  resource :about, controller: :about, only: [:show]

  # Defines the root path route ("/")
  get "/:id" => "home#show", :constraints => {id: /[a-z0-9-]+/}, :as => :photo
  root "home#index"
end

app/models/photo.rb
class Photo < ApplicationRecord
  include PermalinkGenerator

  before_validation :generate_permalink, on: :create, if: -> { author.present? && project.present? }
  after_update_commit :notify_published, if: -> { published? }

  has_rich_text :description

  has_one_attached :image do |attachable|
    attachable.variant :page, resize_to_limit: [900, 900]
    attachable.variant :thumb, resize_to_limit: [48, 48]
  end

  validates :author, :image, :permalink, presence: true

  scope :published, -> { where.not(published_at: nil) }
  scope :unpublished, -> { where(published_at: nil) }

  def published?
    published_at.present?
  end

  def landscape?
    return true if !image.attached?
    image.blob.metadata[:width].to_i > image.blob.metadata[:height].to_i
  end

  def to_param
    permalink
  end

  def meta_description
    "#{author} :: #{project}. #{description.to_plain_text.truncate(130)}".strip
  end

  def notify_published
    Rails.logger.info("Notify published")
    NotifyPublishedJob.perform_later
  end
end

app/controllers/admin/photos_controller.rb
module Admin
  class PhotosController < ApplicationController
    before_action :authenticate_user!

    def index
      @pagy, @photos = pagy(Photo.with_attached_image.includes(image_attachment: :blob).order(created_at: :desc), items: 8)
    end

    def new
      @photo = Photo.new
    end

    def create
      @photo = Photo.new(secure_params)

      if @photo.save
        flash.notice = t("flash.photos.create.notice")
        redirect_to admin_photos_path
      else
        flash.now.alert = t("flash.photos.create.alert")
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @photo = Photo.find_by!(permalink: params[:id])
    end

    def update
      @photo = Photo.find_by!(permalink: params[:id])

      if @photo.update(secure_params)
        flash.notice = t("flash.photos.update.notice")
        redirect_to admin_photos_path
      else
        flash.now.alert = t("flash.photos.update.alert")
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def secure_params
      params.require(:photo).permit(:author, :project, :image, :description, :url)
    end
  end
end

app/views/admin/photos/_form.html.erb
<%# locals: (photo:) -%>

<section class="bg-white">
  <%= form_with model: [:admin, photo], class: "space-y-12 lg:max-w-3xl mx-auto", id: dom_id(photo) do |form| %>
    <div class="border-b border-gray-900/10 pb-12">
      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

        <div class="col-span-full" data-controller="file" data-file-max-size-value="2621440" data-file-validation-message-value="Exceds the maximum file size allowed">
          <%= form.label :image, class: "label" %>

          <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10 relative">
            <div class="container text-center" data-file-target="container" data-image-loaded="<%= photo.image.attached? %>">
              <button type="button" class=" button-accented absolute top-2 left-2 inline-flex replace" data-action="file#select">
                <svg class="h-5 w-5 text-white mr-1" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
                </svg>
                <span class="cursor-pointer"><%= t(".replace_file") %></label>
              </button>

              <div class="placeholder" data-file-target="placeholder">
                <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
                </svg>
                <div class="mt-4 flex text-sm leading-6 text-gray-600">
                  <button type="button" class="mx-auto button-accented" data-action="file#select">
                    <span class="cursor-pointer"><%= t(".upload_file") %></span>
                  </button>
                  <%= form.hidden_field :image, value: photo.image.signed_id if photo.image.attached? %>
                  <%= form.file_field :image, direct_upload: true, accept: "image/png,image/jpeg", class: "hidden", data: {'file-target': 'fileInput'} %>
                </div>
                <p class="text-xs leading-5 text-gray-600 mt-2"><%= t(".upload_file_message") %></p>
              </div>

              <img data-file-target="preview" class="preview" src="<%= photo.image.attached? ? url_for(photo.image) : '' %> " />
              <p class="help help-error" data-file-target="help"></p>

            </div>
          </div>
          <%= error_for(form, :image) %>
        </div>

        <%= text_field_for(form, :author, placeholder: "Bryan Schutmaat", class: "w-full text-lg") %>
        <%= text_field_for(form, :project, placeholder: "Country road", maxlength: 80, class: "w-full") %>
        <%= text_field_for(form, :url, type: :url, placeholder: "https://www.bryanschutmaat.co", maxlength: 100, class: "w-full") %>

        <div class="sm:col-span-6">
          <%= form.label :description, class: "label" %>
          <div class="mt-2 flex flex-wrap-reverse">
            <%= form.rich_text_area :description, autocomplete: :off, placeholder: "County Road", class: "w-full input richtext" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/admin/photos/edit.html.erb
<div class="w-full">
  <section aria-labelledby="photos-heading" class="bg-white max-w-4xl mx-auto">
    <div class="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="px-4 py-16 sm:px-6 lg:px-8">
        <h1 id="photos-heading" class="text-3xl font-bold tracking-tight text-gray-900"><%= t(".title") %></h1>
        <p class="mt-4 max-w-xl text-sm text-gray-700"><%= t(".description") %></p>
      </div>

      <div class="ml-4 mt-2 flex-shrink-0">
        <%= link_to t("back"), admin_photos_path, class: "button mr-2" %>
        <button class="button-accented" form="<%= dom_id(@photo) %>"><%= t(".save_photo") %></button>
      </div>
    </div>
  </section>

  <%= render partial: "form", locals: { photo: @photo } %>
</div>

app/views/admin/photos/index.html.erb
<div class="w-full">
  <section aria-labelledby="photos-heading" class="bg-white">
    <div class="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="px-4 py-16 sm:px-6 lg:px-8">
        <h1 id="photos-heading" class="text-3xl font-bold tracking-tight text-gray-900"><%= t(".title") %></h1>
        <p class="mt-4 max-w-xl text-sm text-gray-700"><%= t(".description") %></p>
      </div>

      <div class="ml-4 mt-2 flex-shrink-0">
        <%= link_to t(".new_photo"), new_admin_photo_path, class: "relative inline-flex items-center rounded-md bg-gray-900 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    </div>
  </section>

  <% if @photos.empty? %>
    <section class="mx-auto px-4 pb-16 pt-12 sm:px-6 sm:pb-24 sm:pt-16 lg:max-w-7xl lg:px-8">
      <div class="text-center">
        <svg class="mx-auto h-12 w-12 text-gray-300" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
        </svg>
        <h3 class="mt-2 text-sm font-semibold text-gray-900"><%= t(".no_photos") %></h3>
        <p class="mt-1 text-sm text-gray-500"><%= t(".add_one") %></p>
        <div class="mt-6">
          <%= link_to t(".new_photo"), new_admin_photo_path, class: "inline-flex items-center rounded-md bg-gray-900 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      </div>
    </section>
  <% else %>
    <section aria-labelledby="photos-list-heading" class="mx-auto px-4 pb-16 pt-12 sm:px-6 sm:pb-24 sm:pt-16 lg:max-w-7xl lg:px-8">
      <h2 id="photos-list" class="sr-only">Inspiration photographies</h2>
    
      <div class="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
        <% @photos.each do |photo| %>
          <%= link_to edit_admin_photo_path(photo), class: "group relative" do %>
            <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-h-8 xl:aspect-w-7">
              <%= image_tag photo.image.variant(:page), class: "w-full h-full object-center object-cover group-hover:opacity-75" %>
            </div>
            <% if photo.published? %>
              <div class="absolute inset-y-1 right-1">
                <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs text-white ring-1 ring-inset ring-gray-200 bg-white/50">
                  <svg class="h-1.5 w-1.5 fill-green-500" viewBox="0 0 6 6" aria-hidden="true">
                    <circle cx="3" cy="3" r="3" />
                  </svg>
                  Published
                </span>
              </div>
            <% end %>
            <h3 class="mt-4 text-sm text-gray-700"><%= photo.author %></h3>
            <% if photo.project.present? %>
              <p class="mt-1 text-sm font-medium text-gray-900"><%= photo.project %></p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </section>
  <% end %>
</div>

<div class="mb-10 ">
  <%= render_responsive_pagination(@pagy) %>
</div>

app/views/admin/photos/new.html.erb
<div class="w-full">
  <section aria-labelledby="photos-heading" class="bg-white max-w-4xl mx-auto">
    <div class="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="px-4 py-16 sm:px-6 lg:px-8">
        <h1 id="photos-heading" class="text-3xl font-bold tracking-tight text-gray-900"><%= t(".title") %></h1>
        <p class="mt-4 max-w-xl text-sm text-gray-700"><%= t(".description") %></p>
      </div>

      <div class="ml-4 mt-2 flex-shrink-0">
        <%= link_to t("back"), admin_photos_path, class: "button mr-2" %>
        <button class="button-accented" form="<%= dom_id(@photo) %>"><%= t(".save_photo") %></button>
      </div>
    </div>
  </section>

  <%= render partial: "form", locals: { photo: @photo } %>
</div>