config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Push subscriptions and notifications
  resource :push_subscriptions, only: [:create, :destroy]

  get "feed", to: "rss#index", format: "rss"
  get "sitemap", to: "sitemap#index", defaults: {format: "xml"}

  resource :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :photos, except: [:show, :destroy]
  end

  scope "/admin" do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
  get "/admin" => "admin/photos#index"

  resource :about, controller: :about, only: [:show]

  # Defines the root path route ("/")
  get "/:id" => "home#show", :constraints => {id: /[a-z0-9-]+/}, :as => :photo
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  allow_unauthenticated_access
  include JsonLdGenerator
  include MetaTagsGenerator

  def index
    @pagy, @photos = pagy(Photo.published.with_attached_image.order(published_at: :desc))
    set_meta

    respond_to do |format|
      format.html
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.append("photos", partial: "photos", locals: {photos: @photos, pagy: @pagy}),
          turbo_stream.remove("next-#{@pagy.page - 1}")
        ]
      end
    end
  end

  def show
    photo_id_param = params[:id].starts_with?("01j") ? {ulid: params[:id]} : {permalink: params[:id]}
    @photo = Photo.published.with_rich_text_description.with_attached_image.find_by!(photo_id_param)
    set_meta(@photo)
  end

  def share?
    true
  end

  private

  def set_meta(resource = nil)
    @json_ld = generate_json_ld(resource)
    generate_meta_tags(resource) if resource.present?
  end
end

app/views/home/_photo.html.erb
<%# locals: (photo:, index:) -%>

<%= link_to photo_path(photo), id: dom_id(photo) do %>
  <%- dimensions = scaled_dimensions(photo.image.metadata[:width], photo.image.metadata[:height], 900) -%>
  <%= image_tag photo.image.variant(:page), alt: photo.author, 
    loading: index >= 3 ? 'lazy' : '', style: "sview-transition-name: #{dom_id(photo)}", 
    class: "w-[900px] h-auto sm:max-h-[900px] sm:max-w-full", width: dimensions[:width],
    height: dimensions[:height] %>
<% end %>
<div class="p-2">
  <h2 class="text-base font-bold"><%= photo.author %></h2>
  <% if photo.project.present? %>
    <p class="text-gray-500"><%= photo.project %></p>
  <% end %>
</div>

app/views/home/_photos.html.erb
<%# locals: (photos:, pagy:) -%>
<%- left = Date.today.day % 2 == 0 -%>

<% photos.each_with_index do |photo, index| %>
  <%- portrait = photo.image.metadata[:width] < photo.image.metadata[:height] -%>
  <% if portrait & left %>
    <article class="col-span-1 md:col-span-4">
      <%= render partial: 'photo', locals: { photo: photo, index: index } %>
    </article>
    <div class="hidden md:block">
    </div>
  <% elsif portrait & !left %>
    <div class="hidden md:block">
    </div>
    <article class="col-span-1 md:col-span-4">
      <%= render partial: 'photo', locals: { photo: photo, index: index } %>
    </article>
  <% else %>
    <article class="col-span-1 md:col-span-6">
      <%= render partial: 'photo', locals: { photo: photo, index: index } %>
    </article>
  <% end %>
<% end %>

<% if pagy.next.present? %>
  <%= turbo_frame_tag "next-#{pagy.page}", src: root_path(page: pagy.next, format: :turbo_stream), loading: :lazy %>
<% end %>

app/views/home/index.html.erb
<header class="bg-white/80 sm:bg-transparent sticky top-0">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-2 px-4 sm:p-1 sm:pt-4" aria-label="Global">
    <div class="flex lg:flex-1 text-gray-900" data-controller="notifications" data-notifications-subscribe-value="<%= push_subscriptions_path %>" data-notifications-unsubscribe-value="<%= push_subscriptions_path %>">
      <%= link_to root_path, class: "text-gray-900 hover:text-gray-700" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2 h-6 w-6">
          <path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3"></path>
        </svg>
      <% end %>

      <%= link_to t("name"), about_path, class: "text-gray-900 hover:text-gray-700 mr-8" %>

      <%= button_to "#", data: { action: "notifications#subscribe", "notifications-target": "subscribeButton" }, class: "hidden" do %>
        <div class="relative flex size-6">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="text-gray-700 hover:text-gray-900 absolute inline-flex h-full w-full" data-notifications-target="subscribeIcon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-gray-700 hover:text-gray-900">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
          </svg>
        </div>
      <% end %>
      <%= button_to "#", data: { action: "notifications#unsubscribe", "notifications-target": "unsubscribeButton" }, class: "hidden" do %>
        <div class="relative flex size-6">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 text-gray-700 hover:text-gray-900 absolute inline-flex h-full w-full" data-notifications-target="unsubscribeIcon">
            <path fill-rule="evenodd" d="M5.25 9a6.75 6.75 0 0 1 13.5 0v.75c0 2.123.8 4.057 2.118 5.52a.75.75 0 0 1-.297 1.206c-1.544.57-3.16.99-4.831 1.243a3.75 3.75 0 1 1-7.48 0 24.585 24.585 0 0 1-4.831-1.244.75.75 0 0 1-.298-1.205A8.217 8.217 0 0 0 5.25 9.75V9Zm4.502 8.9a2.25 2.25 0 1 0 4.496 0 25.057 25.057 0 0 1-4.496 0Z" clip-rule="evenodd" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 text-gray-700 hover:text-gray-900">
            <path fill-rule="evenodd" d="M5.25 9a6.75 6.75 0 0 1 13.5 0v.75c0 2.123.8 4.057 2.118 5.52a.75.75 0 0 1-.297 1.206c-1.544.57-3.16.99-4.831 1.243a3.75 3.75 0 1 1-7.48 0 24.585 24.585 0 0 1-4.831-1.244.75.75 0 0 1-.298-1.205A8.217 8.217 0 0 0 5.25 9.75V9Zm4.502 8.9a2.25 2.25 0 1 0 4.496 0 25.057 25.057 0 0 1-4.496 0Z" clip-rule="evenodd" />
          </svg>
        </div>
      <% end %>
    </div>

    <div class="hidden lg:flex lg:gap-x-12">
    </div>

    <div class="flex flex-1 justify-end">
      <%= link_to t("top"), "#top", class: "text-gray-900 hover:text-gray-700" %>
    </div>

  </nav>
</header>

<section class="bg-white sm:max-w-4xl mx-auto mt-8 mb-12" id="top">
  <div class="grid grid-cols-1 md:grid-cols-6 gap-32" id="photos">
    <%= render partial: 'photos', locals: { photos: @photos, pagy: @pagy } %>
  </div>
</section>

app/views/home/show.html.erb
<header class="md:bg-transparent sticky top-0">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-1 pt-4" aria-label="Global">
    <div class="flex flex-1">
      <%= link_to t("back"), root_path, class: "text-gray-900 hover:text-gray-700", data: { back: true} %>
    </div>

    <div class="hidden lg:flex lg:gap-x-12">
    </div>

    <div class="flex lg:flex-1 text-gray-900 justify-end">
      <%= link_to root_path, class: "text-gray-900 hover:text-gray-700" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2 h-6 w-6">
          <path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3"></path>
        </svg>
      <% end %>

      <%= link_to t("name"), about_path, class: "text-gray-900 hover:text-gray-700" %>
    </div>
  </nav>
</header>

<section class="bg-white max-w-4xl mx-auto mt-8">
  <%- dimensions = scaled_dimensions(@photo.image.metadata[:width], @photo.image.metadata[:height], 900) -%>
  <%= image_tag @photo.image.variant(:page), alt: @photo.author, class: "w-[900px] h-auto sm:max-h-[700px] sm: w-auto mx-auto", 
    style: "sview-transition-name: #{dom_id(@photo)}", width: dimensions[:width], height: dimensions[:height] %>
  <div class="px-2 py-4 mb-6">
    <h2 class="text-base font-bold"><%= @photo.author %></h2>
    <% if @photo.project.present? %>
      <p class="text-gray-500"><%= @photo.project %></p>
      <%= link_to @photo.url, "#{@photo.url}?utm_source=#{request.host}", class: "text-gray-500 hover:text-gray-700", target: "_blank" %>
      <% if @photo.description.present? %>
        <div class="mt-4 text-sm text-gray-700" data-share>
          <%= @photo.description %>
        </div
      <% end %>
    <% end %>
  </div>
</section>