config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Push subscriptions and notifications
  resource :push_subscriptions, only: [:create, :destroy]

  get "feed", to: "rss#index", format: "rss"
  get "sitemap", to: "sitemap#index", defaults: {format: "xml"}

  resource :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :photos, except: [:show, :destroy]
  end

  scope "/admin" do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
  get "/admin" => "admin/photos#index"

  resource :about, controller: :about, only: [:show]

  # Defines the root path route ("/")
  get "/:id" => "home#show", :constraints => {id: /[a-z0-9-]+/}, :as => :photo
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="scroll-smooth" lang="<%= I18n.locale %>">
  <head>
    <%= display_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="view-transition" content="same-origin"/>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= tag.meta name: 'vapid-public-key', content: Rails.application.credentials.vapid[:public_key] %>

    <%= yield :head %>

    <script async src="/es-module-shims.js" data-turbo-track="reload"></script>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(v: 2, format: :json) %>

    <%= auto_discovery_link_tag :rss, feed_url, title: t("name") %>

    <%= tag.link rel: "icon", href: image_path("icon.svg"), type: "image/svg+xml" %>
    <%= tag.link rel: "apple-touch-icon", sizes: "180x180", href: image_path("icon-180x180.png") %>
    <%= tag.link rel: "icon", type: "image/png", sizes: "32x32", href: image_path("icon-32x32.png") %>
    <%= tag.link rel: "icon", type: "image/png", sizes: "16x16", href: image_path("icon-16x16.png") %>
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>

    <script type="application/ld+json">
      <% if @json_ld %>
        <%= raw @json_ld %>;
      <% end %>
    </script>
  </head>

  <body data-controller="service-worker">
    <%= render partial: "alert" %>

    <main class="mt-2 px-0 md:px-5">
      <%= yield %>

      <% if share? %>
        <button class="fixed bottom-4 right-4 z-50 p-2 bg-white rounded-full shadow-md" data-controller="share" data-action="click->share#share">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 sm:size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M7.217 10.907a2.25 2.25 0 1 0 0 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186 9.566-5.314m-9.566 7.5 9.566 5.314m0 0a2.25 2.25 0 1 0 3.935 2.186 2.25 2.25 0 0 0-3.935-2.186Zm0-12.814a2.25 2.25 0 1 0 3.933-2.185 2.25 2.25 0 0 0-3.933 2.185Z" />
          </svg>
        </button>
      <% end %>
    </main>

    <%- if Rails.env.production? -%>
      <script>
        window.op = window.op||function(...args){(window.op.q=window.op.q||[]).push(args);};
        window.op('init', {
          clientId: 'd5db3cb6-e6ad-4cf4-a940-329f548be0a2',
          trackScreenViews: true,
          trackOutgoingLinks: true,
          trackAttributes: true,
        });
      </script>
      <script src="https://openpanel.dev/op1.js" defer async></script>
    <%- end -%>
  </body>
</html>

app/views/layouts/security.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: content_for(:title) || "Inspiration" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= tag.link rel: "icon", href: image_path("icon.svg"), type: "image/svg+xml" %>
    <%= tag.link rel: "apple-touch-icon", sizes: "180x180", href: image_path("icon-180x180.png") %>
    <%= tag.link rel: "icon", type: "image/png", sizes: "32x32", href: image_path("icon-32x32.png") %>
    <%= tag.link rel: "icon", type: "image/png", sizes: "16x16", href: image_path("icon-16x16.png") %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
  </head>

  <body>
    <%= render partial: "alert" %>

    <main class="overflow-hidden">
      <div class="relative h-lvh grid flex-col items-center justify-center px-8 sm:grid lg:max-w-none lg:grid-cols-2 lg:px-0">
        <div class="relative hidden h-full flex-col bg-muted p-10 text-white lg:flex">
          <div class="absolute inset-0 bg-zinc-900"></div>
          <div class="relative z-20 flex items-center text-lg font-medium">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2 h-6 w-6">
              <path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3"></path>
            </svg>
            HeroImage
          </div>
          <div class="relative z-20 mt-auto">
            <blockquote class="space-y-2">
              <p class="text-lg">“Your own photography is never enough. Every photographer who has lasted has depended on other peoples pictures too – photographs that may be public or private, serious or funny but that carry with them a reminder of community.”</p>
              <footer class="text-sm">Robert Adams</footer>
            </blockquote>
          </div>
        </div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>